# Generated by Django 4.0.10 on 2024-07-27 16:41

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_consignataria_servidor_cadastrado_em_and_more'),
        ('consignataria', '0002_consignataria_cadastrado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consignado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamargemathena',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamargemathena',
            name='cadastrado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamargemathena',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamargemathena',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desativado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultamargemathena',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamargemathena',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cadastrado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desativado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultamargemathena',
            name='consignataria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignataria.consignataria'),
        ),
        migrations.AlterField(
            model_name='consultamargemathena',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.servidor'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignado.consultamargemathena'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='situacao',
            field=models.SmallIntegerField(choices=[(0, 'EM ANALISE'), (1, 'DEFERIDO'), (2, 'INDEFERIDO'), (3, 'EXPIRADO')]),
        ),
    ]
