# Generated by Django 4.0.10 on 2024-07-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_consignataria_servidor_cadastrado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMargemAthenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='cadastrado_em',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='desativado_em',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='modificado_por',
        ),
        migrations.AddField(
            model_name='consignataria',
            name='cpf_cnpj',
            field=models.CharField(default='05409790235', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignataria',
            name='nome',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_inicial', models.DateField()),
                ('prazo_final', models.DateField()),
                ('contrato', models.CharField(max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.consultamargemathenas')),
            ],
        ),
        migrations.AddField(
            model_name='consultamargemathenas',
            name='consignataria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.consignataria'),
        ),
        migrations.AddField(
            model_name='consultamargemathenas',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.consulta'),
        ),
        migrations.AddField(
            model_name='consultamargemathenas',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.servidor'),
        ),
    ]
