# Generated by Django 4.0.10 on 2024-07-27 19:28

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consignataria', '0002_consignataria_cadastrado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignataria',
            name='cadastrado_em',
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='desativado_em',
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='desativado_por',
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='consignataria',
            name='modificado_por',
        ),
        migrations.AddField(
            model_name='consignataria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consignataria',
            name='atualizado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignataria',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consignataria',
            name='criado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
