# Generated by Django 4.0.10 on 2024-07-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignataria', '0003_remove_consignataria_cadastrado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMargemAthenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignataria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignataria.consignataria')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignataria.consulta')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignataria.servidor')),
            ],
        ),
    ]
